openapi: 3.0.0
x-api-id: dapi
info:
  title: DAPI
  version: 0.6.1
  description: Dash Decentralized API (DAPI)
servers:
  - url: 'http://dapi-testnet.thephez.com:3999'
    description: Testnet
  - url: '{url}:{port}'
    description: User-defined network
    variables:
      url:
        default: 'http://dapi.dash.org'
      port:
        default: '3000'
x-send-defaults: true
x-headers: []
x-explorer-enabled: true
x-proxy-enabled: true
x-samples-enabled: true
x-samples-languages:
  - curl
  - node
  - ruby
  - javascript
  - python
tags: []
